---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Durante la migrazione dei dati di storage, i backend di storage vengono inseriti manualmente utilizzando le API REST. Durante la migrazione dei dati del provider VASA, i dati vengono esportati dal database Derby esistente e importati nel database MongoDB. 
---
= Migrazione dai tool ONTAP per VMware vSphere 9.xx a 10,3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo spostamento degli strumenti NetApp ONTAP per la configurazione di VMware vSphere dalla versione 9.xx alla 10.x richiede un processo di migrazione a causa degli aggiornamenti e dei miglioramenti significativi del prodotto nelle versioni.

Puoi eseguire la migrazione da strumenti ONTAP per le release VMware vSphere 9.12D1 e 9.13D2 a 10,3.

Se nella configurazione sono presenti datastore NFS e VMFS e nessun datastore vVols, è sufficiente disinstallare ONTAP Tools 9.xx e installare ONTAP Tools 10.x. Tuttavia, se la configurazione contiene datastore vVols, sarà necessario eseguire la migrazione del provider VASA e dell'SRA.

La tabella seguente descrive il processo di migrazione in questi due diversi scenari.

|===
| *Se la configurazione ha datastore vVols* | *Se la configurazione contiene solo datastore NFS e VMFS* 


| Passaggi: 1. link:../migrate/sra-vasa-migration.html["Migrare il provider VASA"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Creare policy di archiviazione VM"] | Passaggi: 1. Rimuovere ONTAP Tools 9.xx dal proprio ambiente. Fare riferimento a  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["Come rimuovere OTV 9.xx dal tuo ambiente"] Articolo della Knowledge Base di NetApp. 2. link:../deploy/quick-start.html["Distribuisci e configura gli strumenti ONTAP per VMware vSphere 10.3"] 3. link:../migrate/sra-vasa-migration.html["Aggiornare il SRA"] 4.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Creare policy di archiviazione VM"] 
|===

NOTE: Dopo la migrazione da tool ONTAP per VMware vSphere 9.xx a 10,3, i datastore vVol che utilizzano il protocollo NVMe/FC non sono più operativi, perché gli strumenti ONTAP 10,3 supportano il protocollo NVMe-of solo con i datastore VMFS.
