---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Durante la migrazione dei dati di storage, i backend di storage vengono inseriti manualmente utilizzando le API REST. Durante la migrazione dei dati del provider VASA, i dati vengono esportati dal database Derby esistente e importati nel database MongoDB. 
---
= Migrazione dai tool ONTAP per VMware vSphere 9.x a 10,3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la migrazione dei dati dello storage, i back-end dello storage vengono gestiti manualmente attraverso le API REST. La migrazione dei dati del provider VASA implica l'esportazione dei dati dal database Derby esistente e l'importazione nel database MongoDB.


NOTE: La migrazione dagli strumenti ONTAP per VMware vSphere 9.XX è necessaria solo quando si utilizzano VASA Provider e vVol.


NOTE: Dopo la migrazione da tool ONTAP per VMware vSphere 9.x a 10,3, i datastore vVol con protocollo NVMe/FC non funzionano perché gli strumenti ONTAP 10,3 supportano solo i datastore NVMe-of con VMFS.

*A proposito di questa attività*

Puoi eseguire la migrazione da strumenti ONTAP per le release VMware vSphere 9.12D1 e 9.13D2 a 10,3.


NOTE: È necessario eseguire il backup OVA dalla versione corrente prima di eseguire l'aggiornamento alle versioni di patch.



== Passaggi comuni di migrazione

. Distribuzione di OVA per gli strumenti ONTAP per VMware vSphere 10,3.
. Aggiungere l'istanza di vCenter Server che si desidera migrare agli strumenti ONTAP per VMware vSphere 10,3. Fare riferimento a link:../configure/add-vcenter.html["Aggiungere istanze di vCenter Server"].
. Integrare il backend di storage localmente utilizzando il plug-in di strumenti ONTAP sul server vCenter. Aggiungi lo storage come storage per la migrazione a livello locale.




== Fasi di migrazione SRA

*Prima di iniziare*

Prima della migrazione, verificare che uno dei siti sia in uno stato protetto e l'altro sia in uno stato di recupero.


NOTE: Non iniziare la migrazione se il failover è stato completato ma la nuova protezione è in sospeso. Prima di procedere con la migrazione, assicurarsi che il processo di protezione sia completato. Se è in corso un failover di test, ripulire il failover di test e avviare la migrazione.

. Per eliminare l'adattatore SRA degli strumenti ONTAP per VMware vSphere 9.xx in VMware Site Recovery, procedere come segue:
+
.. Accedere alla pagina di gestione della configurazione di VMware Live Site Recovery
.. Andare alla sezione *Storage Replication Adapter*.
.. Dal menu puntini di sospensione, selezionare *Reimposta configurazione*.
.. Dal menu puntini di sospensione, selezionare *Elimina*.


. Eseguire queste operazioni sui siti di protezione e ripristino.
+
.. Installare gli strumenti ONTAP per l'adattatore SRA VMware vSphere 10,3 seguendo la procedura descritta in link:../protect/configure-on-srm-appliance.html["Configurare SRA sull'appliance VMware Live Site Recovery"].
.. Nella pagina dell'interfaccia utente di VMware Live Site Recovery, eseguire le operazioni *Discover Arrays* e *Discover Devices* e verificare che i dispositivi vengano visualizzati come prima della migrazione.






== Fasi di migrazione del provider VASA

. Per abilitare la PORTA Derby 1527 sugli strumenti ONTAP esistenti per VMware vSphere, abilitare l'utente root e accedere alla CLI tramite SSH. Quindi, eseguire il seguente comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implementazione di OVA per tool ONTAP per VMware vSphere 10,3.
. Aggiungere l'istanza di vCenter Server che si desidera migrare agli strumenti ONTAP per VMware vSphere 10,3. Vedere link:../configure/add-vcenter.html["Aggiungere un'istanza di vCenter Server"].
. Back-end dello storage integrato in locale dalle API del server vCenter del plug-in remoto. Aggiungi storage come ambito locale per la migrazione.
. Eseguire la seguente API da Swagger o in Postman per la migrazione.
+
Curl -X POST https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration[]

+
Si può accedere a Swagger tramite questo URL: `https://$FQDN_IP_PORT/, per esempio: https://10.61.25.33:8443/[].

+
[]
====
*Metodo HTTP ed endpoint*

Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

|===


| *Metodo HTTP* | *Percorso* 


| POST | /api/v1 
|===
*Tipo di lavorazione*

Asincrono

*Esempio Curl*

Curl -X POST https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs[]

*Esempio di input JSON*

Corpo della richiesta per la migrazione da 9,12 e 9,13:

{ "otv_ip": "10.12.13.45", "vasa_provider_credits": { "username": "vasauser", "password": "*******" } "database_password": "*******" }

Corpo della richiesta per un'altra migrazione delle release:

{ "otv_ip": "10.12.13.45", "vasa_provider_credits": { "username": "vasauser", "password": "*******" }

*Esempio di output JSON*

Viene restituito un oggetto lavoro. È necessario salvare l'identificatore del lavoro per utilizzarlo nel passo successivo.

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running" }

====
. Utilizzare il seguente URI in Swagger per controllare lo stato:
+
[listing]
----
curl https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
Dopo aver completato il processo, esaminare il rapporto sulla migrazione. Questo rapporto è incluso nei dati del lavoro ed è accessibile dalla risposta del lavoro.

. Aggiungi i tool ONTAP per lo storage provider VMware vSphere a vCenter Server e link:../configure/registration-process.html["Registrare il provider VASA"] con i tool ONTAP per VMware vSphere.
. link:../manage/enable-services.html["Attiva provider VASA"] Servizio sui tool ONTAP per VMware vSphere 10,3.
. Stop ai tool ONTAP per il provider di storage VMware vSphere 9,10/9,11/9,12/9,13 il servizio provider VASA dalla console di manutenzione.
+
Non eliminare il provider VASA.

+
Una volta arrestato il vecchio provider VASA, vCenter Server esegue il failover sui tool ONTAP per VMware vSphere. Tutti i datastore e le macchine virtuali sono accessibili e vengono serviti dai tool ONTAP per VMware vSphere.

. I datastore NFS e VMFS migrati dai tool ONTAP per VMware vSphere 9.xx sono visibili nei tool ONTAP per VMware vSphere 10,3 solo dopo l'attivazione del processo di rilevamento del datastore, che potrebbe richiedere fino a 30 minuti. Verificare se gli archivi dati sono visibili nella pagina di panoramica degli strumenti ONTAP per la pagina dell'interfaccia utente del plugin VMware vSphere.
. Eseguire la migrazione delle patch utilizzando la seguente API in Swagger o in Postman:
+
[]
====
*Metodo HTTP ed endpoint*

Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

|===


| *Metodo HTTP* | *Percorso* 


| PATCH | /api/v1 
|===
*Tipo di lavorazione*

Asincrono

*Esempio Curl*

PATCH Curl -X.  https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43[]

*Esempio di input JSON*

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running" }

*Esempio di output JSON*

Viene restituito un oggetto lavoro. È necessario salvare l'identificatore del lavoro per utilizzarlo nel passo successivo.

{ "id": 123, "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35", "status": "running" }

Il corpo della richiesta è vuoto per l'operazione patch.


NOTE: UUID è l'UUID di migrazione restituito in risposta all'API post-migrazione.

Dopo aver eseguito l'API di migrazione delle patch, tutte le VM sono conformi al criterio di storage.

====


.Cosa succederà
Dopo aver completato la migrazione e aver registrato gli strumenti ONTAP 10,3 in vCenter Server, attenersi alla seguente procedura:

* Attendere il completamento di *Discovery*; i certificati verranno aggiornati automaticamente su tutti gli host.
* Consentire un tempo sufficiente prima di avviare le operazioni del datastore e della macchina virtuale. Il periodo di attesa richiesto varia in base al numero di host, datastore e macchine virtuali all'interno della configurazione. La mancata attesa può causare guasti di funzionamento intermittenti.


Dopo l'aggiornamento, se lo stato di conformità della macchina virtuale è obsoleto, riapplicare il criterio di archiviazione attenendosi alla seguente procedura:

. Accedere al datastore e selezionare *Riepilogo* > *Criteri archiviazione VM*.
+
Lo stato di conformità in *conformità ai criteri di archiviazione VM* viene visualizzato come *non aggiornato*.

. Selezionare il criterio Storage VM e la VM corrispondente
. Selezionare *Applica*
+
Lo stato di conformità in *conformità ai criteri di archiviazione VM* è ora visualizzato come conforme.



.Informazioni correlate
* link:../concepts/rbac-learn-about.html["Scopri i tool ONTAP per VMware vSphere 10 RBAC"]
* link:../upgrade/upgrade-ontap-tools.html["Aggiornamento dai tool ONTAP per VMware vSphere 10.x alla 10,3"]

