---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: È necessario creare gruppi di protezione per proteggere un gruppo di macchine virtuali sul sito protetto. 
---
= Configurare siti protetti e di ripristino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare gruppi di protezione per proteggere un gruppo di macchine virtuali sul sito protetto.



== Configurare i gruppi di protezione

.Prima di iniziare
Assicurarsi che i siti di origine e di destinazione siano configurati per:

* È installata la stessa versione di VMware Live Site Recovery
* Macchine virtuali
* Siti di ripristino e protezione associati
* Gli archivi dati di origine e di destinazione devono essere montati sui rispettivi siti


.Fasi
. Accedere a vCenter Server e selezionare *Site Recovery* > *Protection Groups*.
. Nel riquadro *gruppi di protezione*, selezionare *nuovo*.
. Specificare un nome e una descrizione per il gruppo protezione, direzione e selezionare *Avanti*.
. Nel campo *Type*, selezionare l'opzione *Type Field...* come gruppi di datastore (replica basata su array) per NFS e datastore VMFS. Il dominio degli errori non è altro che SVM con replica abilitata. Vengono visualizzate le SVM che hanno implementato solo il peering e che non hanno problemi.
. Nella scheda gruppi di replica, selezionare la coppia di array abilitata o i gruppi di replica che hanno configurato la macchina virtuale, quindi selezionare *Avanti*.
+
Tutte le macchine virtuali presenti nel gruppo di replica vengono aggiunte al gruppo di protezione.

. Selezionare il piano di ripristino esistente o crearne uno nuovo selezionando *Aggiungi al nuovo piano di ripristino*.
. Nella scheda Pronto per il completamento, esaminare i dettagli del gruppo di protezione creato, quindi selezionare *fine*.




== Associare siti protetti e di ripristino

È necessario associare i siti protetti e di ripristino creati utilizzando il client vSphere per consentire l'individuazione dei sistemi di storage mediante Storage Replication Adapter (SRA).

.Prima di iniziare
* È necessario che VMware Live Site Recovery sia installato sui siti protetti e di ripristino.
* È necessario che SRA sia installato nei siti protetti e di ripristino.


.Fasi
. Fare doppio clic su *Site Recovery* nella home page di vSphere Client e selezionare *Sites*.
. Selezionare *oggetti* > *azioni* > *abbina siti*.
. Nella finestra di dialogo *Associa server di Site Recovery Manager*, immettere l'indirizzo del Platform Services Controller del sito protetto, quindi selezionare *Avanti*.
. Nella sezione Select vCenter Server (Seleziona server vCenter), procedere come segue:
+
.. Verificare che vCenter Server del sito protetto venga visualizzato come candidato corrispondente per l'associazione.
.. Immettere le credenziali amministrative SSO, quindi selezionare *fine*.


. Se richiesto, selezionare *Sì* per accettare i certificati di protezione.


.Risultato
I siti protetti e di ripristino vengono visualizzati nella finestra di dialogo oggetti.
