---
permalink: protect/map-network.html 
sidebar: sidebar 
keywords:  
summary: È necessario mappare le reti nel sito protetto e nel sito di ripristino per consentire la comunicazione tra di esse. 
---
= Configurare le mappature di rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare i mapping delle risorse, ad esempio reti di macchine virtuali, host ESXi e cartelle su entrambi i siti, in modo da consentire la mappatura di ciascuna risorsa dal sito protetto alla risorsa appropriata nel sito di ripristino.

È necessario completare le seguenti configurazioni delle risorse:

* Mappature di rete
* Mappature delle cartelle
* Mappature delle risorse
* Datastore segnaposto


.Prima di iniziare
È necessario aver collegato i siti protetti e di ripristino.

.Fasi
. Accedere a vCenter Server e selezionare *Site Recovery* > *Sites*.
. Selezionare il sito protetto e selezionare *Gestisci*.
. Selezionare *mappature di rete* > *nuovo* nella scheda Gestisci per creare una nuova mappatura di rete.
. Nella procedura guidata Crea mappatura di rete, effettuare le seguenti operazioni:
+
.. Selezionare *prepara automaticamente mappature per reti con nomi corrispondenti* e selezionare *Avanti*.
.. Selezionare gli oggetti del data center richiesti per i siti protetti e di ripristino e selezionare *Aggiungi mappature*.
.. Selezionare *Avanti* dopo aver creato correttamente le mappature.
.. Selezionare l'oggetto utilizzato in precedenza per creare la mappatura inversa, quindi selezionare *fine*.




.Risultato
La pagina Network Mappings (Mapping di rete) visualizza le risorse protette del sito e le risorse del sito di ripristino. È possibile seguire la stessa procedura per le altre reti del proprio ambiente.
