---
permalink: protect/map-resource.html 
sidebar: sidebar 
keywords:  
summary: 'È necessario mappare le risorse sul sito protetto e sul sito di ripristino in modo che le macchine virtuali siano configurate per eseguire il failover in un gruppo di host o nell"altro.' 
---
= Configurare le mappature delle risorse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario mappare le risorse sul sito protetto e sul sito di ripristino in modo che le macchine virtuali siano configurate per eseguire il failover in un gruppo di host o nell'altro.

.Prima di iniziare
È necessario aver collegato i siti protetti e di ripristino.


NOTE: In VMware Live Site Recovery, le risorse possono essere pool di risorse, host ESXi o cluster vSphere.

.Fasi
. Accedere a vCenter Server e selezionare *Site Recovery* > *Sites*.
. Selezionare il sito protetto e selezionare *Gestisci*.
. Selezionare *mappature risorse* > *nuovo* nella scheda Gestisci per creare una nuova mappatura delle risorse.
. Nella procedura guidata Create Resource Mapping (Crea mappatura risorse), eseguire le seguenti operazioni:
+
.. Selezionare *prepara automaticamente mappature per risorsa con nomi corrispondenti* e selezionare *Avanti*.
.. Selezionare gli oggetti del data center richiesti per i siti protetti e di ripristino e selezionare *Aggiungi mappature*.
.. Selezionare *Avanti* dopo aver creato correttamente le mappature.
.. Selezionare l'oggetto utilizzato in precedenza per creare la mappatura inversa, quindi selezionare *fine*.




.Risultato
La pagina Resource Mappings (Mapping delle risorse) visualizza le risorse protette del sito e le risorse del sito di ripristino. È possibile seguire la stessa procedura per le altre reti del proprio ambiente.
