---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Affinché VMware Live Site Recovery comunichi con SRA, è necessario aggiornare le credenziali SRA sul server VMware Live Site Recovery se sono state modificate le credenziali. 
---
= Aggiornare le credenziali SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Affinché VMware Live Site Recovery comunichi con SRA, è necessario aggiornare le credenziali SRA sul server VMware Live Site Recovery se sono state modificate le credenziali.

.Prima di iniziare
È necessario aver eseguito i passaggi descritti nell'argomento link:../protect/configure-on-srm-appliance.html["Configurazione di SRA sull'appliance VMware Live Site Recovery"].

.Fasi
. Eseguire i seguenti comandi per eliminare la cartella della macchina per il ripristino dei siti live di VMware memorizzata nella cache degli strumenti ONTAP Password del nome utente:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Eseguire il comando Perl per configurare SRA con le nuove credenziali:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` È necessario disporre di un'unica citazione relativa al valore della password.
+
Viene visualizzato un messaggio di conferma dell'avvenuta memorizzazione delle credenziali di storage. SRA può comunicare con il server SRA utilizzando l'indirizzo IP, la porta e le credenziali forniti.




