---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords:  
summary: 'ONTAP tools per VMware vSphere è una raccolta di strumenti per la gestione del ciclo di vita delle macchine virtuali. Si integra con l"ecosistema VMware e consente il provisioning, la protezione di base e il disaster recovery delle macchine virtuali.' 
---
= Panoramica sui tool ONTAP per VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per VMware vSphere sono un set di strumenti per la gestione del ciclo di vita delle macchine virtuali. Si integra con l'ecosistema VMware per consentire il provisioning dei datastore e fornire una protezione di base per le macchine virtuali.

I tool ONTAP per VMware vSphere sono una raccolta di microservizi scalabili orizzontalmente, basati sugli eventi e implementati come Open Virtual Appliance (OVA). Questa versione è dotata di integrazione API REST con ONTAP.

I tool ONTAP per VMware vSphere sono composti da:

* Funzionalità della macchina virtuale come protezione di base e disaster recovery
* Provider VASA per gestione granulare delle macchine virtuali
* Gestione basata su criteri dello storage
* Storage Replication Adapter (SRA)
* SnapMirror Active Sync (SMAS)

