---
permalink: automation/rest-implementation.html 
sidebar: sidebar 
keywords: ontap tools vmware vsphere rest api reference 
summary: 'Mentre REST stabilisce un insieme comune di tecnologie e Best practice, l"implementazione esatta di ogni API può variare in base alle scelte di progettazione. Prima di utilizzare l"API REST di VMware vSphere 10, è necessario conoscere il modo in cui sono stati progettati i tool ONTAP.' 
---
= Dettagli di implementazione per i tool ONTAP per le API REST di VMware vSphere 10
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mentre REST stabilisce un insieme comune di tecnologie e Best practice, l'implementazione esatta di ogni API può variare in base alle scelte di progettazione. Prima di utilizzare l'API REST di VMware vSphere 10, è necessario conoscere il modo in cui sono stati progettati i tool ONTAP.

Le API REST comprendono diverse categorie di risorse come vCenter e aggregati. Per ulteriori informazioni, consultare la link:../automation/api-reference.html["Riferimento API"]sezione.



== Come accedere all'API REST

Puoi accedere ai tool ONTAP per l'API REST di VMware vSphere 10 tramite l'indirizzo IP del bilanciatore di carico dei tool ONTAP insieme alla porta. L'URL completo contiene diverse parti, tra cui:

* Porta e indirizzo IP degli strumenti ONTAP
* Versione di API
* Categoria di risorsa
* Risorsa specifica


È necessario configurare l'indirizzo IP durante la configurazione iniziale e la porta è sempre 8443. Inoltre, per un'istanza specifica dei tool ONTAP per VMware vSphere 10 la prima parte dell'URL è costante. Solo la categoria di risorse e la risorsa specifica variano in base agli endpoint.


CAUTION: I valori dell'indirizzo IP e della porta riportati negli esempi seguenti sono a solo scopo illustrativo. È necessario modificare questi valori per l'ambiente in uso.

.Esempio di accesso ai servizi di autenticazione
`\https://10.61.25.34:8443/virtualization/api/v1/auth/login`

Questo URL può essere utilizzato per richiedere un token di accesso utilizzando il metodo POST.

.Esempio di elenco dei server vCenter
`\https://10.61.25.34:8443/virtualization/api/v1/vcenters`

Questo URL può essere utilizzato per richiedere un elenco delle istanze del server vCenter definite utilizzando il metodo GET.



== Dettagli HTTP

I tool ONTAP per l'API REST di VMware vSphere 10 utilizzano HTTP e i parametri correlati per agire sulle raccolte e sulle istanze delle risorse. Di seguito sono presentati i dettagli dell'implementazione HTTP.



=== Metodi HTTP

I metodi HTTP o i verbi supportati dall'API REST sono presentati nella tabella seguente.

[cols="15,15,70"]
|===
| Metodo | CRUD | Descrizione 


| OTTIENI | Leggi | Recupera le proprietà degli oggetti per un'istanza o una raccolta di risorse. Questa operazione viene considerata un'operazione di elenco quando viene utilizzata con una raccolta. 


| POST | Creare | Crea una nuova istanza di risorsa in base ai parametri di input. 


| IN PRIMO PIANO | Aggiornare | Aggiorna un'intera istanza di risorsa con il corpo di richiesta JSON fornito. Vengono conservati i valori chiave non modificabili dall'utente. 


| PATCH | Aggiornare | Richiede che all'istanza della risorsa venga applicata una serie di modifiche selezionate nella richiesta. 


| ELIMINARE | Eliminare | Elimina un'istanza di risorsa esistente. 
|===


=== Intestazioni di richiesta e risposta

La tabella seguente riassume le intestazioni HTTP più importanti utilizzate con l'API REST.

[cols="30,15,55"]
|===
| Intestazione | Tipo | Note sull'utilizzo 


| Accettare | Richiesta | Questo è il tipo di contenuto che l'applicazione client può accettare. I valori validi comprendono '\*/*' o `application/json`. 


| x-auth | Richiesta | Contiene un token di accesso che identifica l'utente che invia la richiesta tramite l'applicazione client. 


| Tipo di contenuto | Risposta | Restituito dal server in base all'intestazione della `Accept` richiesta. 
|===


=== Codici di stato HTTP

I codici di stato HTTP utilizzati dall'API REST sono descritti di seguito.

[cols="15,20,65"]
|===
| Codice | Significato | Descrizione 


| 200 | OK | Indica il successo delle chiamate che non creano una nuova istanza di risorsa. 


| 201 | Creato | È stato creato un oggetto con un identificatore univoco per l'istanza di risorsa. 


| 202 | Accettato | La richiesta è stata accettata e un lavoro in background è stato creato per eseguire la richiesta. 


| 204 | Nessun contenuto | La richiesta è stata completata, anche se non è stato restituito alcun contenuto. 


| 400 | Richiesta errata | L'input della richiesta non viene riconosciuto o non è appropriato. 


| 401 | Non autorizzato | L'utente non è autorizzato e deve eseguire l'autenticazione. 


| 403 | Vietato | Accesso negato a causa di un errore di autorizzazione. 


| 404 | Non trovato | La risorsa a cui si fa riferimento nella richiesta non esiste. 


| 409 | Conflitto | Tentativo di creazione di un oggetto non riuscito perché l'oggetto esiste già. 


| 500 | Errore interno | Si è verificato un errore interno generale nel server. 
|===


== Autenticazione

L'autenticazione di un client all'API REST viene eseguita utilizzando un token di accesso. Le caratteristiche rilevanti del token e del processo di autenticazione includono:

* Il client deve richiedere un token utilizzando le credenziali di amministratore di ONTAP Tools Manager (nome utente e password).
* I token sono formattati come token Web JSON (JWT).
* Ogni token scade dopo 60 minuti.
* Le richieste API da un client devono includere il token nell' `x-auth`intestazione della richiesta.


Fare riferimento alla link:../automation/first-call.html["La prima chiamata API REST"] per un esempio di richiesta e utilizzo di un token di accesso.



== Richieste sincrone e asincrone

La maggior parte delle chiamate API REST vengono completate rapidamente e quindi eseguite in modo sincrono. In altre parole, restituiscono un codice di stato (ad esempio 200) dopo il completamento di una richiesta. Le richieste che richiedono più tempo per essere completate vengono eseguite in modo asincrono utilizzando un processo in background.

Dopo aver emesso una chiamata API che viene eseguita in modo asincrono, il server restituisce un codice di stato HTTP 202. Ciò indica che la richiesta è stata accettata ma non ancora completata. È possibile eseguire una query sul processo in background per determinarne lo stato, incluso il successo o l'errore.

L'elaborazione asincrona è impiegata per diversi tipi di operazioni con esecuzione prolungata, incluse le operazioni di datastore e vVol. Per ulteriori informazioni, fare riferimento alla categoria di gestione lavori dell'API REST nella pagina Swagger.
