---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 'Associare un backend dello storage con vCenter Server per creare una mappatura tra il backend dello storage e l"istanza di vCenter Server integrata a livello globale.' 
---
= Associazione di un backend dello storage a un'istanza di vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Associare un backend dello storage con vCenter Server per creare una mappatura tra il backend dello storage e l'istanza di vCenter Server integrata a livello globale.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona vCenter dalla barra laterale.
. Seleziona i puntini di sospensione verticali rispetto all'istanza di vCenter Server da associare ai backend dello storage.
. Seleziona il backend dello storage dal menu a discesa per associare l'istanza di vCenter Server al backend dello storage richiesto.

