---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: Quando si eseguono per la prima volta i tool ONTAP per VMware vSphere in un client vSphere, i tool ONTAP per VMware vSphere scoprono gli host ESXi, le relative LUN e le esportazioni NFS e i sistemi storage NetApp che gestiscono tali LUN ed esportazioni. 
---
= Rilevamento di host e sistemi storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si eseguono per la prima volta i tool ONTAP per VMware vSphere in un client vSphere, i tool ONTAP rilevano gli host ESXi, le loro LUN e le esportazioni NFS e i sistemi storage NetApp che gestiscono tali LUN ed esportazioni.

.Prima di iniziare
* Tutti gli host ESXi devono essere accesi e connessi.
* Tutte le Storage Virtual Machine (SVM) da rilevare devono essere in esecuzione e ogni nodo del cluster deve avere almeno una LIF dati configurata per il protocollo storage in uso (NFS o iSCSI).


*A proposito di questa attività*

È possibile scoprire nuovi sistemi storage o aggiornare le informazioni sui sistemi storage esistenti per ottenere le informazioni più aggiornate sulla capacità e sulla configurazione in qualsiasi momento. Puoi anche modificare le credenziali utilizzate dai tool di ONTAP per VMware vSphere per accedere ai sistemi storage.

Durante il rilevamento dei sistemi storage, i tool di ONTAP per VMware vSphere raccolgono informazioni dagli host ESXi gestiti dall'istanza di vCenter Server.

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Fare clic con il pulsante destro del mouse sul centro dati desiderato e selezionare *NetApp ONTAP tools* > *Update host Data* (Strumenti *aggiornamento dati host*).
+
Nella finestra di dialogo *Conferma*, confermare la scelta.

. Selezionare i controller di archiviazione rilevati che hanno lo stato `Authentication Failure` e selezionare *azioni* > *Modifica*.
. Inserire le informazioni richieste nella finestra di dialogo *Modify Storage System* (Modifica sistema di storage).
. Ripetere i passaggi 4 e 5 per tutti i controller di archiviazione con `Authentication Failure` stato.


Al termine del processo di rilevamento, eseguire le seguenti operazioni:

* Utilizzare gli strumenti ONTAP per VMware vSphere per configurare le impostazioni dell'host ESXi per gli host che visualizzano l'icona di avviso nella colonna delle impostazioni dell'adattatore, nella colonna delle impostazioni MPIO o nella colonna delle impostazioni NFS.
* Fornire le credenziali del sistema storage.

