---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Puoi installare il plug-in NFS NetApp per le API vStorage di VMware per l"integrazione degli array \(VAAI\) utilizzando i tool ONTAP per VMware vSphere.' 
---
= Installare il plug-in NFS VAAI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in NFS vStorage API for Array Integration (NFS VAAI) è un componente software che integra gli storage array VMware vSphere e NFS. Installa il plug-in NFS VAAI utilizzando i tool di ONTAP per VMware vSphere per sfruttare le funzionalità avanzate dello storage array NFS e scaricare alcune operazioni legate allo storage dagli host ESXi allo storage array stesso.

.Prima di iniziare
* Scaricare il https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plug-in NetApp NFS per VMware VAAI"] pacchetto di installazione.
* Assicurarsi di disporre dell'host ESXi e della patch più recente di vSphere 7.0U3 o versioni successive e di ONTAP 9.14.1 o versioni successive.
* Montare un datastore NFS.


.Fasi
. Accedere al client vSphere.
. Selezionare *tasti di scelta rapida* > *NetApp ONTAP tools* nella sezione dei plug-in.
. Selezionare *Impostazioni* > *NFS VAAI Tools*.
. Quando il plug-in VAAI viene caricato su vCenter Server, seleziona *Cambia* nella sezione *versione esistente*. Se un plug-in VAAI non viene caricato in vCenter Server, selezionare il pulsante *carica*.
. Sfogliare e selezionare il `.vib` file e selezionare *carica* per caricare il file negli strumenti ONTAP.
. Selezionare *Installa su host ESXI*, selezionare l'host ESXi su cui si desidera installare il plug-in NFS VAAI, quindi selezionare *Installa*.
+
Vengono visualizzati solo gli host ESXi idonei per l'installazione del plug-in. È possibile monitorare l'avanzamento dell'installazione nella sezione attività recenti del client web vSphere.

. Riavviare l'host ESXi manualmente dopo l'installazione.
+
Quando l'amministratore VMware riavvia l'host ESXi, i tool ONTAP per VMware vSphere rilevano e attivano automaticamente il plug-in NFS VAAI.



.Quali sono le prossime novità?
Dopo aver installato il plug-in NFS VAAI e riavviato l'host ESXi, occorre configurare le policy di esportazione NFS corrette per l'offload delle copie VAAI. Durante la configurazione di VAAI in un ambiente NFS, configurare le regole delle policy di esportazione tenendo presenti i seguenti requisiti:

* Il volume ONTAP rilevante deve consentire NFSv4 chiamate.
* L'utente root deve rimanere come root e NFSv4 deve essere consentito in tutti i volumi padre di giunzione.
* L'opzione per il supporto VAAI deve essere impostata sul relativo server NFS.


Per ulteriori informazioni sulla procedura, fare riferimento all' https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Configura le policy di esportazione NFS corrette per l'offload delle copie VAAI"]articolo della Knowledge base.

.Informazioni correlate
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Supporto per VMware vStorage su NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Attivare o disattivare NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["Supporto ONTAP per NFSv4.2"]
