---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 'Quando si fa clic con il pulsante destro del mouse sull"oggetto del datastore nella vista oggetto vCenter, gli strumenti ONTAP per le azioni supportate da VMware vSphere vengono visualizzati nella sezione del plug-in.' 
---
= Espandere il datastore vVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si fa clic con il pulsante destro del mouse sull'oggetto del datastore nella vista oggetto vCenter, gli strumenti ONTAP per le azioni supportate da VMware vSphere vengono visualizzati nella sezione del plug-in. Le azioni specifiche vengono attivate in base al tipo di datastore e ai privilegi dell'utente corrente.


NOTE: L'operazione del datastore Expand vVol non è applicabile al datastore vVol basato su ASA R2.

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Nel riquadro di navigazione, selezionare il centro dati che contiene l'archivio dati.
. Fare clic con il pulsante destro del mouse sul datastore e selezionare *Strumenti NetApp ONTAP* > *Aggiungi storage al datastore*.
. Nella finestra *crea o Seleziona volumi*, è possibile creare nuovi volumi o scegliere tra quelli esistenti. L'interfaccia utente è autoesplicativa. Seguire le istruzioni a scelta.
. Nella finestra *Riepilogo*, rivedere le selezioni e selezionare *Espandi*. È possibile tenere traccia dell'avanzamento nel pannello attività recenti.

