---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords:  
summary: I vCenter sono piattaforme di gestione centrali che consentono di controllare host, macchine virtuali e backend di storage. 
---
= Gestire le istanze di vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le istanze di vCenter Server sono piattaforme di gestione centrali che consentono di controllare host, macchine virtuali e backend dello storage.



== Dissociare i backend di storage con l'istanza di vCenter Server

La pagina dell'elenco di vCenter Server mostra il numero associato di backend storage. Ogni istanza di vCenter Server può essere associata o dissociata da un backend dello storage.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona l'istanza vCenter Server richiesta dalla barra laterale.
. Seleziona i puntini di sospensione verticali su vCenter Server che desideri associare o dissociare dai backend di storage.
. Selezionare *dissociare il backend di archiviazione*.




== Modificare un'istanza di vCenter Server

Per modificare le istanze di vCenter Server, procedere come segue.

. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona l'istanza vCenter Server applicabile dalla barra laterale
. Selezionare le ellissi verticali a fronte di vCenter Server che si desidera modificare e selezionare *Modifica*.
. Modificare i dettagli dell'istanza di vCenter Server e selezionare *Modifica*.




== Rimuovere un'istanza di vCenter Server

Prima di rimuoverlo, devi rimuovere tutti i backend dello storage collegati a vCenter Server.

. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona le istanze vCenter Server applicabili dalla barra laterale
. Selezionare le ellissi verticali sul vCenter Server che si desidera rimuovere e selezionare *Rimuovi*.
+

NOTE: Una volta rimosse le istanze di vCenter Server, queste non verranno più gestite dall'applicazione.



Quando si rimuovono le istanze di vCenter Server negli strumenti ONTAP, vengono eseguite automaticamente le seguenti azioni:

* Plug-in non registrato.
* I privilegi dei plug-in e i ruoli dei plug-in vengono rimossi.

