---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Se si è dimenticata la password di ONTAP Tools Manager, è possibile reimpostare le credenziali di amministratore utilizzando il token generato dagli strumenti ONTAP per la console di manutenzione di VMware vSphere. 
---
= Reimpostare la password di gestione degli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se hai dimenticato la password di ONTAP Tools Manager, puoi reimpostare le credenziali di amministratore utilizzando il token generato dagli strumenti ONTAP per la console di manutenzione di VMware vSphere.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Nella schermata di accesso, selezionare l'opzione *Reimposta password*.
+
Per reimpostare la password di Manager, è necessario generare il token di reimpostazione utilizzando gli strumenti ONTAP per la console di manutenzione di VMware vSphere.

+
.. Da vCenter Server, aprire la console di manutenzione
.. Immettere '2' per selezionare l'opzione Configurazione di sistema
.. Immettere '3' per modificare la password utente 'Mainta'.


. Nella finestra a comparsa di modifica della password, immettere il token di reimpostazione della password, il nome utente e i dettagli della nuova password.
. Selezionare *Reimposta* per implementare le modifiche. Una volta reimpostata correttamente la password, è possibile utilizzare la nuova password per accedere.

