---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: È possibile aggiornare le credenziali vCenter Server e ONTAP utilizzando la console di manutenzione. 
---
= Aggiornare le credenziali vCenter Server e ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare l'istanza di vCenter Server e le credenziali ONTAP utilizzando la console di manutenzione.

.Prima di iniziare
È necessario disporre delle credenziali di accesso per gli utenti di manutenzione.

*A proposito di questa attività*

Se sono state modificate le credenziali per vCenter Server, ONTAP o Data LIF dopo la distribuzione, è necessario aggiornare le credenziali utilizzando questa procedura.

.Fasi
. Dal server vCenter, aprire una console per il provider VASA.
. Accedere come utente di manutenzione.
. Inserire `2` per selezionare il menu Configurazione di sistema.
. Immettere `9` per modificare le credenziali ONTAP.
. Immettere `10` per modificare le credenziali vCenter.

